---
- name: install haproxy
  yum:
    name: haproxy
- name: start haproxy
  service:
    name: haproxy
    state: started
    enabled: True
- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
