---
- name: install ntp
  yum:
    name: ntp
    state: latest
- name: configure ntp
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp
- name: start ntp
  service:
    name: ntpd
    state: started
    enabled: True
  tags: ntp
