---

# http://serverfault.com/questions/638507/how-to-access-host-variable-of-a-different-host-with-ansible
- name: gather facts from db servers
  hosts: db
  tasks: [ ]

- name: configure web servers
  hosts: web
  remote_user: vagrant
  become: True
  vars:
    db_user: dbuser
    db_password: abc123

  tasks:
    - name: install httpd, php, php-mysql
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
       - httpd
       - php
       - php-mysql
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: True
    - name: create the index.php file
      template:
        src: index.php.j2
        dest: /var/www/html/index.php
    - name: create headers.conf file
      template:
          src: headers.conf.j2
          dest: /etc/httpd/conf.d/headers.conf
      notify: restart httpd
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
